### ISSUE TITLE
Hitting "Failure: multiple findlib packages have an identical name."

### ISSUE THREAD

**Issue by smondet** [solvuu/solvuu-build#25]
I don't really understand why they need to be unique:
https://github.com/solvuu/solvuu-build/blob/1137763f73094d5803649bf42b5eecf3a57ca9af/lib/solvuu_build_findlib.ml#L81

And I don't see why my code is problematic:
https://github.com/hammerlab/coclobas/blob/solvuu-build-problem/myocamlbuild.ml

```ocaml
let ketrew_backend : Project.item option =
  let item =
    Project.lib (project_name ^ "_ketrew_backend")
      ~thread:()
      ~findlib_deps:("ketrew" :: [])
      ~dir:"src/ketrew_backend"
      ~pack_name:(project_name ^ "_ketrew_backend")
      ~internal_deps:[lib]
      ~pkg:project_name
  in
  if Project.dep_opts_sat item ["ketrew"]
  then Some item
  else None
```

**Comment by smondet** [comment]
oh the error was not from `findlib_deps` but from `~pkg:project_name`.

**Comment by agarwal** [comment]
Right, the `pkg` arg defines the findlib package name of the library you are creating, so you do want those to be unique.
