### ISSUE TITLE
refactor code

### ISSUE THREAD

**Issue by agarwal** [solvuu/solvuu-build#28]
@rleonid The discussion we had regarding how to structure the code got more significant after 7bf9574b5ad4e40b1a7638b19d406e1cb0309d7d. We now need to do something only for native compilation, so I end up case analyzing on the mode within an iteration over the modes. This is silly and the code is practically illegible now.

**Comment by leo** [comment]
Wrong username :blush:

**Comment by agarwal** [comment]
@leo Sorry about that!

**Comment by rleonid** [comment]
Yes, this is a growing concern. I wonder if we can use a polymorphic variant to describe the build up of state.

```
val preprocess : unit -> [`WithSource of _ ]
val compute_dependents : [ `WithSource of _ ] -> [ `SourceAndDependends of _ ]
val compile : mode list -> [ `SourceAndDependends of _ ] -> [ `Modules _ ]
```

**Comment by agarwal** [comment]
I made several commits that improves the situation. None go as far as you're suggesting.

**Comment by agarwal** [comment]
I feel the code is actually pretty clean now. I'll close this issue in a few days unless we get some concrete ideas for how to improve it further.
