### ISSUE TITLE
Missing depencies between internal libs

### ISSUE THREAD

**Issue by pveber** [solvuu/solvuu-build#36]
**Symptom**: I have an app A that depends on lib B which itself depends on lib C. When I modify C, neither A nor B are recompiled. An invocation of `ocamlbuild -documentation` shows that while A has a dep on B, B has no dep on C. Actually, each cm[o|x|i] should have a dep on C.cm[a|x].

I think this could be fixed by adding internal libs cma/cmxa as dependencies [here](https://github.com/solvuu/solvuu-build/blob/master/lib/project.ml#L775) and [there](https://github.com/solvuu/solvuu-build/blob/master/lib/project.ml#L796).

**Comment by smondet** [comment]
👍 I think I have observed the same issue. I often have to `make clean; make` because of `inconsistent assumptions`.

**Comment by agarwal** [comment]
Done in 60b02e1f10f0c93c625de301ce8b841d930ae927.

**Comment by pveber** [comment]
Great, thanks!
