### ISSUE TITLE
Help with basic project

### ISSUE THREAD

**Issue by bluddy** [solvuu/solvuu-build#38]
I'm trying to use solvuu-build on a very basic project (one file) to get a feel for it.

Here's my myocamlbuild.ml:
```
open Solvuu_build.Std

let project_name = "images"
let version = "dev"

let app = Project.app "hw1"
    ~file:"hw1.ml"

let () = Project.basic1 ~project_name ~version [app]
```

I get the errors
```
/Users/yotambarnoy/.opam/4.03.0+flambda/lib/solvuu-build/solvuu.mk:3: _build/project.mk: No such file or directory
ocamlbuild -use-ocamlfind -plugin-tag "package(solvuu-build)" project.mk
Finished, 0 targets (0 cached) in 00:00:00.
Failure: findlib packages have no root.
Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
make: *** [_build/project.mk] Error 2
```

Am I doing something wrong?

**Comment by smondet** [comment]
Not wrong, but too simple for solvuu-build :)

You're hitting this: https://github.com/solvuu/solvuu-build/issues/22

(the idea is that if your project does not have a library, then `ocamlbuild` can build it in one commmand, so, so far nobody implemented that)

**Comment by agarwal** [comment]
#22 is now resolved.

@bluddy Apologies for not getting to this sooner. Something is wrong with my GitHub notifications. I tried your example, and it now works fine. Let us know if we can help further.
