### ISSUE TITLE
libs with multiple directories

### ISSUE THREAD

**Issue by agarwal** [solvuu/solvuu-build#49]
Allow the files for a single library to be placed in multiple directories.

**Comment by tekknolagi** [comment]
How is progress on this?

**Comment by agarwal** [comment]
I'll work on this in the next couple of days.

**Comment by tekknolagi** [comment]
Awesome.

**Comment by agarwal** [comment]
I pushed a fix to a new branch `issue-49`. It would be great if I could get confirmation that it works for others. I tested on one project and it seems okay to me.

**Comment by tekknolagi** [comment]
@agarwal how should I test it? Docs?

**Comment by agarwal** [comment]
You'll have to pin to that branch with something like `opam pin add solvuu-build https://github.com/solvuu/solvuu-build.git#issue-49`. Then simply use as usual but the `dir` used to create a lib should include sub-directories.

Do you have an existing repo you're trying it on? I just wanted validation it works for your specific use case, but that is moot if you would be trying solvuu-build for the first time.

**Comment by tekknolagi** [comment]
@agarwal Yes, but it did not previously use solvuu-build. There was an attempt, which ended after the realization that it did not handle multiple directories.

**Comment by agarwal** [comment]
I went ahead and merged 647393d02999d03258f5951422691cf85178109b to master. Please ask more questions if it is unclear how to use it, but I'll close this issue for now.
