### ISSUE TITLE
Support -inline-max-depth and -inline-max-unroll flags

### ISSUE THREAD

**Issue by copy** [solvuu/solvuu-build#50]
Related to #42, I would like to specify these flags. See https://caml.inria.fr/pub/docs/manual-ocaml/flambda.html#speculation. `-rounds` might be useful too.

**Comment by agarwal** [comment]
Done in cd092caf9015ae17010b2804f7868906c1729a3f.

Note I used a `string` type for all `inline*` flag values. The format for all is `<n>|<round>=<n>[,...]`, so an `int` is not sufficient and a stronger type like ```[`Int of int | `List of (int * int) list]``` seemed overkill.
