### ISSUE TITLE
js_of_ocaml rule

### ISSUE THREAD

**Issue by copy** [solvuu/solvuu-build#55]
solvuu-build already has a command for js_of_ocaml, for convenience it could also provide a rule.

**Comment by agarwal** [comment]
We could argue also for `ocamlc_rule`, `ocamlopt_rule`, `ocamlfind_ocamlc_rule`, etc. Looking at uses in `Project`, I see that often `foo_rule` wouldn't help and one would have to call `foo` anyway, but there are few places it would shorten the code. So I'm happy to add this if you would find it useful. Want to make a pull request?

**Comment by copy** [comment]
Fixed by 32b98ab158e1c93f80bc4d72b241fd519022c8d6.
