### ISSUE TITLE
Additional makefile targets

### ISSUE THREAD

**Issue by copy** [solvuu/solvuu-build#56]
Some new pseudo-targets would be useful for working in larger projects (in my example, I'm have 15 apps. In most cases I don't want to build everything):

1. `make $item` should build the app or lib with the given name, i.e. the `.byte` or library
2. `make $item-native` same as 1. but native version
3. `make $item-run` should build and run the application
4. `make $item-run-native` like 3. but native
5. `make run` should run all (or any single) applications, mostly useful in small projects with only a single application

**Comment by copy** [comment]
I've had a look and this would be relatively easy to implement. @agarwal would you accept a PR for these changes?

**Comment by agarwal** [comment]
IIUC, proposal 1 would replace `make _build/foo.byte` with `make foo`, and proposal 2 would replace `make _build/foo.native` with `make foo-native`. I'm not convinced this is helpful. It seems more confusing to me.

I don't understand proposals 3 - 5. How can you run an app in general. Every app has different arguments, so what exactly would you do in the general case.

Would it be sufficient for you to write your own `build_makefile` rule. It is very easy to avoid the one solvuu-build provides, and provide your own.

**Comment by copy** [comment]
> IIUC, proposal 1 would replace make _build/foo.byte with make foo, and proposal 2 would replace make _build/foo.native with make foo-native. I'm not convinced this is helpful. It seems more confusing to me.

Yes, I'd find it quite useful, I'm building several apps and my paths are deeper than `_build/appname.native`. I'd also say that it's less confusing to be able to type `make foo` in order to build everything specified by `Project.app "foo" …`.

> I don't understand proposals 3 - 5. How can you run an app in general. Every app has different arguments, so what exactly would you do in the general case.

I guess this isn't proper use of `make` (I like abusing `make` just for muscle memory at times 😉), although adding arguments is [technically possible](http://stackoverflow.com/a/2214593/5046452). My primary use-case would be small projects without arguments or running tests or benchmarks in a bigger project.

I don't want to insist on these changes, I think they are niceties to have. If not, I'll go with writing my own rule.

**Comment by agarwal** [comment]
I hope you don't mind but I'll pass on this feature request. I'm not seeing the benefit.

> I'm building several apps and my paths are deeper than `_build/appname.native`

Fair enough. I can see that is more cumbersome, but I'd argue that you're trading one benefit for another. Typing `make appname` is an extra level of indirection; now you're wondering what exactly is being built. The more explicit `make _build/a/b/c/appname.native` is more clear about that, though longer.

> type make foo in order to build everything specified by `Project.app "foo"`

Definition of _everything_ is unclear. `Project.app "foo"` defines an app. The only clear build artifact that provides is `foo.byte` and `foo.native` but you're already proposing 2 separate rules for those 2 items. The other build artifacts that get _affected_ are `.install`, `.merlin`, but only partly. These files are also affected by all the other items you define.

> My primary use-case would be small projects without arguments

This seems highly specific.

In addition to defining your own `build_makefile` rule, keep in mind that you can simply add rules in your Makefile.

**Comment by copy** [comment]
> I hope you don't mind but I'll pass on this feature request. I'm not seeing the benefit.

Sure, no worries. I'll close it then.
