### ISSUE TITLE
Slowness due to repeatedly building static files

### ISSUE THREAD

**Issue by copy** [solvuu/solvuu-build#58]
I'm currently experimenting with improved merlin generation, so I'm creating my own merlin file and registering it using `build_static_file ".merlin" my_merlin_content`. Generating the content takes a few seconds, which usually shouldn't be a problem since the merlin file isn't rebuilt all too often.

However, since ocamlbuild is called multiple times during a build and `build_static_file` takes the content directly, my merlin generation is called multiple times, slowing down the build process. Instead, `build_static_file` should accept a callback to be called when the file should be built, for example like shown below.

```ocaml
let build_static_file_lazy path content_fn =
  let path = Filename.normalize path in
  Ocamlbuild_plugin.rule path ~prod:path (fun _ _ ->
    let content = List.map (content_fn ()) ~f:(sprintf "%s\n") in
    Seq [
      Cmd (Sh (sprintf "mkdir -p %s" (Filename.dirname path)));
      Echo (content, path);
    ]
  )

let () =
  build_static_file_lazy ".merlin" (fun () -> merlin_file projects)
```

The same method should also be used to build the built-in static files in solvuu-build. I can create a patch if you're interested.

**Comment by agarwal** [comment]
Can you help me understand how your solution works. Ocamlbuild still re-generates the file on every invocation AFAICT. Where is the speedup going to come from? I'm not seeing how moving the content generation to within the rule changes anything because ultimately `merlin_file` still gets called each time.

Another solution could be to declare `myocamlbuild.ml` a dependency of `.merlin` (and `.ocamlinit`). Would that resolve the problem more cleanly?

A third possibility is to add the following to the generated Makefile:
```
_build/.merlin:
	$(OCAMLBUILD) $(patsubst _build/%,%,$@)
```

**Comment by copy** [comment]
> Can you help me understand how your solution works. Ocamlbuild still re-generates the file on every invocation AFAICT. Where is the speedup going to come from? I'm not seeing how moving the content generation to within the rule changes anything because ultimately merlin_file still gets called each time.

I believe this is due to the interaction between make and ocamlbuild: make invokes ocamlbuild several times to build separate files. I'm not sure about the specifics of ocamlbuild's rule invocation, but empirically my observation holds:

```
$ make
Finished, 1 target (0 cached) in 00:00:00.
>>> build_static_file register: .merlin
>>> build_static_file register: .ocamlinit
>>> build_static_file register: project.mk
>>> build_static_file call: project.mk
Finished, 1 target (0 cached) in 00:00:00.
ocamlbuild -use-ocamlfind -plugin-tag "package(solvuu-build)" .merlin
Finished, 0 targets (0 cached) in 00:00:00.
>>> build_static_file register: .merlin
>>> build_static_file register: .ocamlinit
>>> build_static_file register: project.mk
>>> build_static_file call: .merlin
Finished, 1 target (0 cached) in 00:00:00.
rm -f .merlin
ln -fs _build/.merlin .merlin
ocamlbuild -use-ocamlfind -plugin-tag "package(solvuu-build)" .ocamlinit
Finished, 0 targets (0 cached) in 00:00:00.
>>> build_static_file register: .merlin
>>> build_static_file register: .ocamlinit
>>> build_static_file register: project.mk
>>> build_static_file call: .ocamlinit
Finished, 1 target (0 cached) in 00:00:00.
rm -f .ocamlinit
ln -fs _build/.ocamlinit .ocamlinit
ocamlbuild -use-ocamlfind -plugin-tag "package(solvuu-build)" src/test.byte
Finished, 0 targets (0 cached) in 00:00:00.
>>> build_static_file register: .merlin
>>> build_static_file register: .ocamlinit
>>> build_static_file register: project.mk
Finished, 1 target (0 cached) in 00:00:00.
```

```ocaml
open Solvuu_build.Std
open Solvuu_build.Util
let sprintf = Printf.sprintf

let build_static_file path content_fn =
  Printf.printf ">>> build_static_file register: %s\n" path;
  let path = Filename.normalize path in
  Ocamlbuild_plugin.rule path ~prod:path (fun _ _ ->
    Printf.printf ">>> build_static_file call: %s\n" path;
    let content = List.map (content_fn ()) ~f:(sprintf "%s\n") in
    Seq [
      Cmd (Sh (sprintf "mkdir -p %s" (Filename.dirname path)));
      Echo (content, path);
    ]
  )

let myapp = Project.app "test"
    ~color:`always
    ~g:()
    ~w:"-40"
    ~findlib_deps:[]
    ~file:"src/app.ml"

let projects = [myapp]

let () =
  let libs = Project.filter_libs projects in
  let apps = Project.filter_apps projects in

  Ocamlbuild_plugin.dispatch @@ function
  | Ocamlbuild_plugin.After_rules -> (
      Ocamlbuild_plugin.clear_rules ();

      List.iter ~f:Project.build_lib libs;
      List.iter ~f:Project.build_app apps;

      build_static_file ".merlin" (fun () -> Project.merlin_file projects);
      build_static_file ".ocamlinit" (fun () -> Project.ocamlinit_file projects);
      build_static_file "project.mk" (fun () -> Project.makefile projects ~project_name:"test");
    )
  | _ -> ()
```

**Comment by pveber** [comment]
Since `ocamlbuild` handles dependencies already, maybe you could write a
`Makefile` that does a single invocation of `ocamlbuild` instead of writing
multiple targets with dependencies?

2017-02-27 4:58 GMT+01:00 Fabian <notifications@github.com>:

**Comment by copy** [comment]
@pveber That would indeed also solve this problem and could also improve speed in general (see #52).

My solution also has the advantage that it enables caching, so that static files are only rebuilt when certain files (only the `myocamlbuild`?) change.

**Comment by agarwal** [comment]
> Since `ocamlbuild` handles dependencies already, maybe you could write a `Makefile` that does a single invocation of `ocamlbuild` instead of writing multiple targets with dependencies?

Done in 6c8fea5769b54ba4acf1dc71f82ab88d6ba74165. This is helpful independent of this issue.

I'm still investigating options for avoiding re-build of static files, the original request of this issue.

**Comment by agarwal** [comment]
I tried two things:

- Adding `myocamlbuild.ml` as a dependency to `.merlin` and other static files. I didn't notice any performance improvement. Although this might be logically the correct thing to do, I'm not bothering to add it since there is no clear benefit currently.

- Making the content creation lazy. This of course avoids building the content until the rule is really run (not sure why I didn't see that right away). If your content creation takes a few seconds, then of course this will help. I've gone ahead and pushed this change in 09df582d9ba2c672cad432166bb21c9e5869f148. There's no reason to keep the current `build_static_file`, so I've simply changed that one. This is a backwards incompatible change, and I've documented that `Changes.md`.

@copy I'm curious what you're doing that takes so long to generate a .merlin file.

**Comment by copy** [comment]
> @copy I'm curious what you're doing that takes so long to generate a .merlin file.

I'm invoking [opamfind](https://bitbucket.org/camlspotter/opamfind) to find the opam packages corresponding to the ocamlfind packages of the current build, and then I'm adding the build paths to the merlin file. opamfind takes some time to analyse the associations between opam and ocamlfind packages.

If you're interested, I can send a PR for these changes, adding opamfind as an optional dependency.

**Comment by agarwal** [comment]
> I'm invoking opamfind

Cool. I didn't know about `opamfind`. It seems a little unstable though for us to assume it can be used by everyone, e.g. it requires `OPAMKEEPBUILDDIR=yes` to have been always set and relies on making a system call to `opam`.

However, we could add support for this in `Tools`. At least you could have a function that runs `opamfind` and returns the list of packages parsed and available as an OCaml `string list`. Such functions are prefixed with `run_`.

Please close this issue if you feel the original issue here has been resolved.

**Comment by copy** [comment]
> Please close this issue if you feel the original issue here has been resolved.

Yep, cheers.
